#!/bin/bash
#$1 is ip of interface to bind to

if [ $# -lt  1 ]
then
   echo "USAGE: tp_test_server [ip to bind to]"
   exit 
fi

echo "starting iperf server bound to ip:" $1; 

iperf3 -f m -s -B $1 --logfile ./iperf3log

echo "iperf server running"
