#!/bin/bash
#$1 is ip of interface to bind to

if [ $# -lt  2 ]
then
   echo " tp_test_client [ip to connect to] [ip to bind to]"
   exit 
fi

echo "starting iperf client bound to ip:" $2;

iperf3 -f m -c $1 -B $2 -Z

